services:
  - type: web
    name: portfolio-api
    env: docker
    dockerfilePath: ./backend/ContactApi/Dockerfile
    dockerContext: ./backend/ContactApi
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: OWNER_EMAIL
        sync: false
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FRONTEND_URL
        value: https://portfolio-fe-swapnil-guptas-projects-2fb8af3d.vercel.app
